# Generated by Django 2.2.4 on 2019-08-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
    ]
